"""Pin CLIP's output across a `transformers` upgrade.

Why this test exists
--------------------
`requirements.txt` carried no `transformers` pin at all, and moving the
installed 4.35.0 to >=4.50 crosses the release where `from_pretrained` starts
handing back a **fast** image processor by default instead of the slow PIL one.
Resize filter, rescale order and the resample used for the 224x224 crop all
live on that seam. If any of them shifts, every *new* embedding is computed in
a slightly different space from the ~1,800 vectors already in `embeddings` —
and nothing raises. Search just quietly gets worse, because cosine between a
4.35-era vector and a 4.5x-era vector for the same photo is no longer 1.0.

There is no cheap way to detect that after the fact. So the vector below is
checked in: it is what `ClipEmbedder.image_embedding` returned for a
synthetic image on `transformers==4.35.0`, and it is the thing a dependency
bump has to reproduce.

Reading nothing
---------------
The input image is *generated here*, from integer arithmetic only — no photo,
no MinIO object, no fixture file on disk. `/dev/sda` (which holds all media) is
failing; this test must not depend on it, and it must not depend on a binary
fixture that could be regenerated by accident. Integer-only construction also
means the pixels are bit-identical on any numpy/PIL version, so a mismatch can
only come from the model or its preprocessing, never from the input.

Running it
----------
Gated behind `CHITRA_TEST_LOAD_MODELS=1` so the default suite stays fast and
keeps torch out of the runner:

    CHITRA_TEST_LOAD_MODELS=1 CHITRA_DB_PATH=/tmp/chitra_test.db \
        .venv/bin/python tests/run_tests.py test_embedder_stability

To regenerate the reference (only ever when the *model* is deliberately
changed — never to make a red test green):

    CHITRA_TEST_LOAD_MODELS=1 .venv/bin/python tests/test_embedder_stability.py

**Do not widen `TOLERANCE` to get past a failure.** A failure here means the
stored corpus and future embeddings have diverged, which makes the dependency
bump a forced full re-embed, not a version number.
"""
from __future__ import annotations

import base64
import hashlib
import os
import tempfile
import unittest

import numpy as np

# Fixed seed for the deterministic dither below. Not a numpy RNG seed: the
# dither is a hand-rolled LCG so the bytes do not depend on numpy's generator
# stream, which is only loosely version-stable.
SEED = 20260901
IMAGE_SIZE = 256

# SHA-256 of the generated RGB array's raw bytes. Asserted separately from the
# vector so a failure says *which* half moved: if this digest still matches and
# the vector does not, the model or its preprocessing changed. If the digest
# itself fails, the image generator changed and the reference vector below is
# meaningless until it is regenerated.
IMAGE_SHA256 = "890cf4e29e75d47f836ec793c5b17f92b2457236a15ae56354fef5a8c30f826f"

MODEL_NAME = "openai/clip-vit-base-patch32"
EXPECTED_DIM = 512

# Max absolute per-component difference. CLIP's 512-d unit vectors have an RMS
# component of ~0.044, so 1e-4 is ~0.2% of a typical component — loose enough
# for CPU float32 reassociation across thread counts, tight enough that a
# changed resize filter cannot hide in it.
TOLERANCE = 1e-4

# base64 float32[512], produced by `python tests/test_embedder_stability.py`
# under transformers==4.35.0 / torch==2.9.1 / pillow==10.4.0.
REFERENCE_B64 = (
    "v2+bO5sHHLtNiwU81/IyvU6ufjwu1Ri9+YWTPLPmjD1UwE899ivhPOuimbxmjfK7W/UtvYfb0Ltr"
    "Uz48IzIoPMf6Hr3Vukk7bkmHunHy8jzZ34w8m11LvUKqFz384QY8+X89vBPSuDx1bwk8UNGsPMvp"
    "szvkGvO5MakTPCKMK7xxvmi6UKl0PEC3jLueF0+9me8kPAyA9zxB1VG8aYavvUKgXLsHo5E7cG0P"
    "veeGmTtxihW7HwISvCl78rx+yLu8QRMfPTa9CLw86qG8q+yYvAI5jDw3j4K836Tpu+Vn8zxH4568"
    "DjBmvCwAirw3c6O8BQaau6lCBDyyhQK6vjOJuybP4byxEZk8FUHVuvl4WLwnxQY8vD5ZPJzDML1N"
    "vk25Wzd2PNOgJz1W14A72iPjvOf1dTxPBam8JF+eu3Q4Ljv5DyC8gjUMvf5jRLwK9Za72v0CPB4F"
    "Oj23szM9w/BEvC0uxDzl9ym8m1UYPIOIuTwjVz+/ye+IuwQYmrvmJH47niwtPeWLQby7GLI6NEmF"
    "vYarazwJIVm7J8y0PJedgbqiogm6BtHAuwyxRL7d9hU8KUdEvC4acjzY0Gq97Z+AvTgYsLuvMhK9"
    "cLSkvM+esDxBUwk89DgFvatsu7sMO1o9Lnw5ux+M+bt5y7a6mqRUPHgNpDvDipG7W/1nvIY2J7zq"
    "vBk96CyJPVemYbyYJnw88HKVvBVqsT11D0o9oEqnPB0CwzxfD4y9er5VvE9k4TzoqrG8LKeAPDc/"
    "Xby0sNY7dAcTvQQFTrxlnC88V1hLPFlDWjxNzVK8zcYmvJzwkTxrB38934itOyhgp7x1HZ07s7sJ"
    "PTUU1jyKeDe87vZQPX6zpLt7WCk8ID54u75tgjz4Hjk8lI8sPUVstzvVKoS7xc1OvRb/hzyO/2+8"
    "/7ugu0DFdbzT06a8yc1vPBeshTxpkmG91K5XPOUQCLtVumG894S5vClymTxGX3m8BeWkutG6qryI"
    "HxS9JNs0PJga/DtH+wg8q7sovFGAFjwkbFc7rW/jPL5bQzzeEBg9GriYOz3vwLwwA66892HpO71/"
    "HTzAZ4k8BM06PJDx2jx5gaE6Wm3ovKsvDrpma2g8ty9WPCl3rjwKEgA75PfBvKsccD24VdW8OGb4"
    "vE9JvrvJuAC9H7MEu/BNs7z4vnE73ca7vBGusjwp5se8FCwNO32t6Lz+kSY89ACPPHWyZTyevxw7"
    "egqMOt5IQzwV1pW8l2GRPOmWMDsFUmy9GJ/ivGEd9TuYmzm8vIr/vBHg+bzW+m86jC0RvaCKA7wa"
    "zBc9dZddPMOkoruaWwS8quG1vBQiEbyrJyg9SXVkvBysprsKBhK8sFgIvchlrrvb7sE7Bb8avCPA"
    "3jzj9Z68IC0Dvqx5mrwk7Yk8if4SvBxObL108FS8HhUqPBnbOLquNSq7+nDGPGO4ITyeswE9rnMY"
    "vW+aMTxvo5e768DCvOoXFrv8u009bgcEvVyCgD3NOxW70oHpuv3uIjxB2dU801I5PaPvQTr++UA9"
    "j2YxPTsfpTyJ1Tk8ex30PBfFhju+3xI85qKRO3ZRGLzZ8UO81xqsvFowWD2VKdq9erekvMz7NruM"
    "uQW9sPY3PSxIM7u9X4K8VtNJPASKmLuCWi+877uBPIld2zwab746tdwUvIgHiLzW1ek6jTyxPY9X"
    "fLzSwHu8XiKDPHf9i7wum/m6whMBvPiyjLwjzLa8T6eBPvqEOjzOWiw9Gf0mvADXHL2tNai8grRF"
    "PFLmlbrc7Qc9Ooffu/1fCz3SrLa8kIEtvGwCs7wfMki8phHZPDWVGzxyAZm7X9WWul/T1jy7o2o7"
    "I+j2vMl8DL0Mw4I8Tqu6PIs0Jrwc8a68nRjIPBf7CzxBfoi74PkYvCXY97tr2um7qohgPFiR5zkC"
    "/2M91H1NPeVgwLyfYiI9PRJUvZxu+LtUc1m8X3r/O8cifL3XcVS9jr/3uzfnbzzG3PQ8xBcHvIib"
    "NDyOJas8rTDoO51J7jzjZBM8tMY1vIadejuY5eI7OQfZvNDHKDybWbe7+fYGvFaYBT11to48nuS3"
    "PGcWTjveaF47BXLQvD5OpbiUG2c9NoZ9vEmgTb3U/7C8TrBMOtE86buFZE88qwqAPBdr0jrUBN68"
    "ilCqvFFqqrw6HrU6pfXPvNX7D7zgtZi6qqJBvE19E71zfrY8NMacOjTTlrx4zZE9rkdova2cRTgW"
    "xA08qoYvPVwZHrzhAOi8cQkcvf+4crrhAYY4SfK8vKXsTbx0uGO95+SgvfmGkDymiUc8MdeFPIu0"
    "gjxND/631VmKPDOPqLx269m87/eyvFteqTw18kk8OZKQOf00YTzpe0e9fp2dvK5sG7wPzlo8sbva"
    "vHtqxjsHUAQ8dHASPPgWoLwgpNI8g6ZoPF+E+jxzkbG8ZzIbPYjYg7zapzc8iPjjvK9ZuDz8Fcu7"
    "InYVvWN5tjvgQEI8M/jBvFG0o7yZJYQ4Rd69vMHsGr2Znbw8wB5xvCbnDT05Epg8j/qZu2vbFrsa"
    "9sM8VzX7OpRFNrzBb5e8Z05BPOO5uTyb7xI9DsDNu/SpsLsST4A8+1CUu+Y0EL3XLxe9aq3FPDD3"
    "ezu2RPK7qGFJPKfBzzzspba8ZbemvKXyiDtwvJy8FHgrPKetkLyiD5q7atLnOg8mkTu1ksm8AM1O"
    "vaW8dr3u80Q9onsEPce5DDu/YQm79e1rPMdJHT2L04E77YiIvFB5gryFHY88PgS2vIIcgTs="
)


def synthetic_image_array() -> np.ndarray:
    """A deterministic 256x256 RGB test pattern, built from integers only.

    Three independent structures so the embedding is not degenerate: a
    horizontal ramp, a vertical ramp, an XOR interference field, plus a 32px
    checkerboard and a per-pixel LCG dither. The dither matters — a smooth
    gradient alone is nearly scale-invariant, which is exactly the signal a
    changed resize filter would destroy without changing the vector much.
    """
    h = w = IMAGE_SIZE
    yy, xx = np.mgrid[0:h, 0:w].astype(np.int64)

    # Linear congruential dither over the flat pixel index. Integer ops only.
    lcg = ((yy * w + xx) * 1103515245 + SEED) & 0x7FFFFFFF
    dither = (lcg >> 11) & 0x1F

    ramp_x = (xx * 255) // (w - 1)
    ramp_y = (yy * 255) // (h - 1)
    interference = (xx ^ yy) & 0xFF
    checker = (((xx // 32) + (yy // 32)) & 1) * 47

    r = (ramp_x + checker) & 0xFF
    g = (ramp_y + dither) & 0xFF
    b = (interference + checker) & 0xFF

    return np.stack([r, g, b], axis=-1).astype(np.uint8)


def write_synthetic_png(path: str) -> None:
    from PIL import Image

    Image.fromarray(synthetic_image_array(), mode="RGB").save(path, format="PNG")


def embed_synthetic() -> np.ndarray:
    """Embed the synthetic pattern with the production `ClipEmbedder`."""
    from core.embedder import ClipEmbedder

    embedder = ClipEmbedder(MODEL_NAME)
    fd, path = tempfile.mkstemp(suffix=".png", prefix="clip-stability-")
    os.close(fd)
    try:
        write_synthetic_png(path)
        return embedder.image_embedding(path)
    finally:
        try:
            os.unlink(path)
        except OSError:
            pass


def _decode_reference() -> np.ndarray:
    raw = base64.b64decode(REFERENCE_B64.encode("ascii"))
    return np.frombuffer(raw, dtype="<f4")


LOAD_MODELS = os.environ.get("CHITRA_TEST_LOAD_MODELS") == "1"


class TestSyntheticImageIsDeterministic(unittest.TestCase):
    """Runs unconditionally — it loads no model."""

    def test_pattern_bytes_are_pinned(self):
        arr = synthetic_image_array()
        self.assertEqual(arr.shape, (IMAGE_SIZE, IMAGE_SIZE, 3))
        self.assertEqual(arr.dtype, np.uint8)
        digest = hashlib.sha256(arr.tobytes()).hexdigest()
        self.assertEqual(
            digest,
            IMAGE_SHA256,
            "the synthetic test pattern changed; the reference vector no longer "
            "describes this image and must be regenerated on the *old* "
            "transformers before any upgrade is judged",
        )

    def test_pattern_has_structure(self):
        # A constant or near-constant image would make the reference vector
        # meaningless as a preprocessing probe.
        arr = synthetic_image_array()
        self.assertGreater(int(arr.std()), 40)
        self.assertEqual(int(arr.min()), 0)
        self.assertEqual(int(arr.max()), 255)

    def test_reference_is_checked_in(self):
        self.assertTrue(
            REFERENCE_B64,
            "REFERENCE_B64 is empty — regenerate it by running this module as a "
            "script on the currently-installed transformers",
        )
        ref = _decode_reference()
        self.assertEqual(ref.shape, (EXPECTED_DIM,))
        self.assertAlmostEqual(float(np.linalg.norm(ref)), 1.0, places=5)


@unittest.skipUnless(
    LOAD_MODELS, "set CHITRA_TEST_LOAD_MODELS=1 to load CLIP (~1.7 GB, ~10 s)"
)
class TestClipEmbeddingIsStable(unittest.TestCase):
    """The safety net for the transformers bump."""

    @classmethod
    def setUpClass(cls):
        cls.vector = embed_synthetic()

    def test_shape_and_norm_unchanged(self):
        self.assertEqual(self.vector.shape, (EXPECTED_DIM,))
        self.assertEqual(self.vector.dtype, np.dtype("float32"))
        self.assertAlmostEqual(float(np.linalg.norm(self.vector)), 1.0, places=5)

    def test_matches_checked_in_reference(self):
        ref = _decode_reference()
        delta = np.abs(self.vector - ref)
        max_delta = float(delta.max())
        cosine = float(np.dot(self.vector, ref))
        self.assertLess(
            max_delta,
            TOLERANCE,
            "CLIP image preprocessing or weights moved: max |delta| "
            f"{max_delta:.3e} (tolerance {TOLERANCE:.0e}), cosine {cosine:.6f}. "
            "Every new embedding now lives in a different space from the ones "
            "already stored. Do NOT relax the tolerance — revert the dependency "
            "change and report, because the alternative is a full re-embed.",
        )

    def test_repeated_embedding_is_reproducible(self):
        """Guards the tolerance itself: run-to-run jitter must be well under it."""
        again = embed_synthetic()
        self.assertLess(float(np.abs(again - self.vector).max()), TOLERANCE / 10)


def _regenerate() -> None:
    import transformers

    arr = synthetic_image_array()
    print(f"image sha256: {hashlib.sha256(arr.tobytes()).hexdigest()}")
    vec = embed_synthetic()
    print(f"transformers: {transformers.__version__}")
    print(f"dim: {vec.shape[0]}  norm: {np.linalg.norm(vec):.8f}")
    print("REFERENCE_B64 = (")
    blob = base64.b64encode(vec.astype("<f4").tobytes()).decode("ascii")
    for i in range(0, len(blob), 76):
        print(f'    "{blob[i:i + 76]}"')
    print(")")


if __name__ == "__main__":
    _regenerate()
